#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  echo "Usage: $0 <hts_path> <rabbitbam_path> <libdeflate_path>"
  exit 1
fi

HTS_PATH=$1
RABBITBAM_PATH=$2
LIBDEFLATE_PATH=$3

sed -i "s|^HTSLIB_INSTALL_PATH=.*|HTSLIB_INSTALL_PATH=$HTS_PATH|g" Makefile
sed -i "s|^RABBITBAM_INSTALL_PATH=.*|RABBITBAM_INSTALL_PATH=$RABBITBAM_PATH|g" Makefile
sed -i "s|^LIBDEFLATE_INSTALL_PATH=.*|LIBDEFLATE_INSTALL_PATH=$LIBDEFLATE_PATH|g" Makefile

cat <<EOL > env.sh
HTSLIB_INSTALL_PATH=$HTS_PATH
RABBITBAM_INSTALL_PATH=$RABBITBAM_PATH
LIBDEFLATE_INSTALL_PATH=$LIBDEFLATE_PATH

export LD_LIBRARY_PATH=\$HTSLIB_INSTALL_PATH/lib:\$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=\$HTSLIB_INSTALL_PATH/lib64:\$LD_LIBRARY_PATH
export INCLUDE=\$HTSLIB_INSTALL_PATH/include:\$INCLUDE
export CPATH=\$HTSLIB_INSTALL_PATH/include:\$CPATH

export LD_LIBRARY_PATH=\$RABBITBAM_INSTALL_PATH:\$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=\$LIBDEFLATE_INSTALL_PATH/lib:\$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=\$LIBDEFLATE_INSTALL_PATH/lib64:\$LD_LIBRARY_PATH
export INCLUDE=\$LIBDEFLATE_INSTALL_PATH/include:\$INCLUDE
export CPATH=\$LIBDEFLATE_INSTALL_PATH/include:\$CPATH
EOL

echo "Updated HTSLIB_INSTALL_PATH in Makefile to $HTS_PATH"
echo "Updated RABBITBAM_INSTALL_PATH in Makefile to $RABBITBAM_PATH"
echo "Updated LIBDEFLATE_INSTALL_PATH in Makefile to $LIBDEFLATE_PATH"
echo "Generated new env.sh with HTSLIB_INSTALL_PATH, RABBITBAM_INSTALL_PATH, and LIBDEFLATE_INSTALL_PATH"

